:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Global variables
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

CALL %* 
EXIT /B


:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Global functions
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:CopyAttackServiceFiles

ECHO[
ECHO Copying HttpReverseProxy(lib) ...

SET ROOT_DIR=%1
SET ATTACKSERVICES_DIR=%2
SET HTTPREVERSEPROXY_DSTDIR=%ATTACKSERVICES_DIR%HttpReverseProxy\
SET HTTPREVERSEPROXY_ROOT=%ROOT_DIR%Tools\HttpReverseProxy\HttpReverseProxy\bin\%SOLUTIONCONFIG%\
SET PLUGINS_DSTDIR=%HTTPREVERSEPROXY_DSTDIR%plugins\

SET SSLSTRIP_ROOT=%ROOT_DIR%Tools\HttpReverseProxy\SSLStrip\bin\%SOLUTIONCONFIG%\
SET SSLSTRIP_DSTDIR=%HTTPREVERSEPROXY_DSTDIR%plugins\SslStrip

SET CLIENTREQUESTSNIFFER_ROOT=%ROOT_DIR%Tools\HttpReverseProxy\ClientRequestSniffer\bin\%SOLUTIONCONFIG%\
SET CLIENTREQUESTSNIFFER_DSTDIR=%HTTPREVERSEPROXY_DSTDIR%plugins\ClientRequestSniffer

SET WEAKEN_ROOT=%ROOT_DIR%Tools\HttpReverseProxy\Weaken\bin\%SOLUTIONCONFIG%\
SET WEAKEN_DSTDIR=%HTTPREVERSEPROXY_DSTDIR%plugins\Weaken

SET INJECTFILE_ROOT=%ROOT_DIR%Tools\HttpReverseProxy\InjectFile\bin\%SOLUTIONCONFIG%\
SET INJECTFILE_DSTDIR=%HTTPREVERSEPROXY_DSTDIR%plugins\InjectFile

SET INJECTCODE_ROOT=%ROOT_DIR%Tools\HttpReverseProxy\InjectCode\bin\%SOLUTIONCONFIG%\
SET INJECTCODE_DSTDIR=%HTTPREVERSEPROXY_DSTDIR%plugins\InjectCode

SET REQUESTREDIRECT_ROOT=%ROOT_DIR%Tools\HttpReverseProxy\RequestRedirect\bin\%SOLUTIONCONFIG%\
SET REQUESTREDIRECT_DSTDIR=%HTTPREVERSEPROXY_DSTDIR%plugins\RequestRedirect

SET HOSTMAPPING_ROOT=%ROOT_DIR%Tools\HttpReverseProxy\HostMapping\bin\%SOLUTIONCONFIG%\
SET HOSTMAPPING_DSTDIR=%HTTPREVERSEPROXY_DSTDIR%plugins\HostMapping

MKDIR %HTTPREVERSEPROXY_DSTDIR%
MKDIR %PLUGINS_DSTDIR%
MKDIR %SSLSTRIP_DSTDIR%
MKDIR %CLIENTREQUESTSNIFFER_DSTDIR%
MKDIR %WEAKEN_DSTDIR%
MKDIR %INJECTFILE_DSTDIR%
MKDIR %INJECTCODE_DSTDIR%
MKDIR %REQUESTREDIRECT_DSTDIR%
MKDIR %HOSTMAPPING_DSTDIR%

ECHO COPY %HTTPREVERSEPROXY_ROOT%HttpReverseProxy.exe %HTTPREVERSEPROXY_DSTDIR%
COPY %HTTPREVERSEPROXY_ROOT%HttpReverseProxy.exe %HTTPREVERSEPROXY_DSTDIR% >>%OUTPUTFILE%
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

ECHO COPY %HTTPREVERSEPROXY_ROOT%HttpReverseProxyLib.dll %HTTPREVERSEPROXY_DSTDIR% 
COPY %HTTPREVERSEPROXY_ROOT%HttpReverseProxyLib.dll %HTTPREVERSEPROXY_DSTDIR% >>%OUTPUTFILE%
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

ECHO COPY %HTTPREVERSEPROXY_ROOT%NativeWindowsLib.dll %HTTPREVERSEPROXY_DSTDIR% 
COPY %HTTPREVERSEPROXY_ROOT%NativeWindowsLib.dll %HTTPREVERSEPROXY_DSTDIR% >>%OUTPUTFILE%
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

ECHO COPY %HTTPREVERSEPROXY_ROOT%FluentCommandLineParser.dll %HTTPREVERSEPROXY_DSTDIR%
COPY %HTTPREVERSEPROXY_ROOT%FluentCommandLineParser.dll %HTTPREVERSEPROXY_DSTDIR% >>%OUTPUTFILE%
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

ECHO COPY %SSLSTRIP_ROOT%SSLStrip.dll %SSLSTRIP_DSTDIR%\ 
COPY %SSLSTRIP_ROOT%SSLStrip.dll %SSLSTRIP_DSTDIR%\ >>%OUTPUTFILE%
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

ECHO COPY %CLIENTREQUESTSNIFFER_ROOT%ClientRequestSniffer.dll %CLIENTREQUESTSNIFFER_DSTDIR%
COPY %CLIENTREQUESTSNIFFER_ROOT%ClientRequestSniffer.dll %CLIENTREQUESTSNIFFER_DSTDIR% >>%OUTPUTFILE%
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

ECHO COPY %WEAKEN_ROOT%Weaken.dll %WEAKEN_DSTDIR%
COPY %WEAKEN_ROOT%Weaken.dll %WEAKEN_DSTDIR% >>%OUTPUTFILE%
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

ECHO COPY %INJECTFILE_ROOT%InjectFile.dll %INJECTFILE_DSTDIR%
COPY %INJECTFILE_ROOT%InjectFile.dll %INJECTFILE_DSTDIR% >>%OUTPUTFILE%
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

ECHO COPY %INJECTCODE_ROOT%InjectCode.dll %INJECTCODE_DSTDIR%
COPY %INJECTCODE_ROOT%InjectCode.dll %INJECTCODE_DSTDIR% >>%OUTPUTFILE%
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

ECHO COPY %REQUESTREDIRECT_ROOT%RequestRedirect.dll %REQUESTREDIRECT_DSTDIR% 
COPY %REQUESTREDIRECT_ROOT%RequestRedirect.dll %REQUESTREDIRECT_DSTDIR% >>%OUTPUTFILE%
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

ECHO COPY %HOSTMAPPING_ROOT%HostMapping.dll %HOSTMAPPING_DSTDIR% 
COPY %HOSTMAPPING_ROOT%HostMapping.dll %HOSTMAPPING_DSTDIR% >>%OUTPUTFILE%
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

EXIT /B 0
